#!/usr/bin/env bash 

set -e

./node_modules/.bin/eslint frontend resources/scripts
./node_modules/.bin/jscs frontend resources/scripts
find frontend -name *.ts | \
  xargs ./node_modules/.bin/tslint -c tslint.json