#!/usr/bin/env python

import sys
import os

common_dir_path = os.path.realpath(os.path.dirname(__file__) + '/..')
sys.path.insert(0, common_dir_path)
import _common.command_line_helpers as cl_helpers

cl_helpers.help_if_no_args("""
Arguments:
- [required] path to the directory
""")

dir_path = sys.argv[1]

command = 'grep -E "^[[:blank:]]*debugger(;)?" -rnwl ' + dir_path
cl_helpers.print_and_run(command)
