var d = diagrams.box.generateDefinition,
    ds = function(lib) {
        return d(lib, s('libraries-' + lib));
    },
    c = diagrams.box.generateContainer,
    s = diagrams.shared.get;

diagrams.box({
    name: s('project') + ' used libraries',
    body: [
        c('npm', [
            c('dependencies', [
                d('es6-module-loader'),
                d('googleapis', "'Google APIs Client Library for Node.js'"),
                d('gulp-insert'),
                d('gulp-modify'),
                d('gulp-replace'),
                d('node-uuid'),
                d('reflect-metadata', "'Polyfill for Metadata Reflection API. Proposal to add Decorators to ES7, along with a prototype for an ES7 Reflection API for Decorator Metadata'"),
                d('rx', "'Library for composing asynchronous and event-based operations in JavaScript'"),
                d('selenium-webdriver'),
                d('systemjs', "'System loader extension for flexible AMD & CommonJS support'"),
                d('traceur'),
                d('which', "'Locate a program or locally installed node module's executable'"),
                d('zone.js', "'Informs angular.js when to run 'change detection''"),
            ]),
            c('devDependencies', [
                d('angular'),
                d('bower'),
                d('broccoli', "'Browser compilation library – an asset pipeline for applications that run in the browser'"),
                d('broccoli-filter'),
                d('broccoli-flatten'),
                d('broccoli-funnel'),
                d('broccoli-lodash'),
                d('broccoli-merge-trees'),
                d('broccoli-slow-trees'),
                d('broccoli-stew'),
                d('broccoli-writer'),
                d('canonical-path'),
                d('chokidar', "'A neat wrapper around node.js fs.watch / fs.watchFile / fsevents.'"),
                d('clang-format', "'Node repackaging of the clang-format native binary'"),
                d('conventional-changelog'),
                d('css', "'Require css from npm'"),
                d('del', "'Delete files/folders using globs'"),
                d('dgeni', "'Flexible JavaScript documentation generator used by AngularJS'"),
                d('dgeni-packages'),
                d('event-stream'),
                d('firefox-profile', "'firefox profile for selenium WebDriverJs, admc/wd or any other node selenium driver that supports capabilities'"),
                d('fs-extra'),
                d('glob'),
                d('gulp'),
                d('gulp-autoprefixer'),
                d('gulp-changed'),
                d('gulp-clang-format'),
                d('gulp-concat'),
                d('gulp-connect'),
                d('gulp-load-plugins'),
                d('gulp-rename'),
                d('gulp-sass'),
                d('gulp-shell'),
                d('gulp-sourcemaps'),
                d('gulp-template'),
                d('gulp-traceur'),
                d('gulp-typescript'),
                d('gulp-uglify'),
                d('gulp-webserver'),
                d('html2jade'),
                d('indent-string'),
                d('jasmine'),
                d('jasmine-core'),
                d('jpm', "'Jetpack Mechanic utilities for creating, testing, running and packaging Mozilla Jetpack Addons'"),
                d('js-beautify'),
                d('js-yaml'),
                d('karma'),
                d('karma-chrome-launcher'),
                d('karma-cli'),
                d('karma-dart'),
                d('karma-jasmine'),
                d('karma-sauce-launcher'),
                d('lodash'),
                d('madge', "'Create graphs from your CommonJS or AMD module dependencies'"),
                d('marked'),
                d('merge'),
                d('merge2'),
                d('minimatch'),
                d('minimist'),
                d('mock-fs'),
                d('node-html-encoder'),
                d('parse5', "'WHATWG HTML5 specification-compliant, fast and ready for production HTML parsing/serialization toolset for Node and io.js.'"),
                d('protractor'),
                d('q'),
                d('react'),
                d('rewire', "'Easy dependency injection for node.js unit testing'"),
                d('run-sequence'),
                d('semver'),
                d('shelljs', "'Portable Unix shell commands for Node.js'"),
                d('sorted-object'),
                d('source-map'),
                d('sprintf-js', "'sprintf.js is a complete open source JavaScript sprintf implementation for the browser and node.js.' Strings format"),
                d('string'),
                d('strip-ansi'),
                d('symlink-or-copy'),
                d('systemjs-builder'),
                d('temp'),
                d('ternary-stream', "'Fork stream based on passed condition, and collect down-stream'"),
                d('through2', "'Tiny wrapper around Node streams2 Transform to avoid explicit subclassing noise'"),
                d('ts2dart'),
                d('tsd'),
                d('typescript'),
                d('vinyl', "'A virtual file format'"),
                d('walk-sync'),
                d('xtend', "' basic utility library which allows you to extend an object by appending all of the properties from each object in a list.'"),
                d('yargs', "'Light-weight option parsing with an argv hash. No optstrings attached.'"),

            ])
        ]),
        c('bower', [
            c('root', [
                d('polymer')
            ]),
            c('docs', [
                d('angular-material', "'Material Design is a specification for a unified system of visual, motion, and interaction design that adapts across different devices.'"),
                d('google-code-prettify'),
            ])
        ])
    ]
});
