var np = diagrams.graph.generatePrivateNode,
  nl = diagrams.graph.generateNodeWithTextAsTargetLink('../api-overview'),
  ct = diagrams.graph.generateConnectionWithText,
  connectionFnFactory = diagrams.graph.connectionFnFactory,
  cti = connectionFnFactory(ct, 'direction', 'in'),
  ctd = connectionFnFactory(ct, 'line', 'dotted'),
  ctid = connectionFnFactory(cti, 'line', 'dotted');

diagrams.graph([
  nl('function proxy', 0, '/src/test_lib/test_lib.ts'),
  np('var _global', 1, '/src/test_lib/test_lib.ts'),
  nl('var afterEach', [2, ct(1, '_global.afterEach')], '/src/test_lib/test_lib.ts'),
  nl('interface NgMatchers extends jasmine.Matchers', [3, ct(1, '_global.afterEach')], '/src/test_lib/test_lib.ts'),
  nl('var expect', [4, ct(1, '_global.expect'), ct(3, '=> NgMatchers')], '/src/test_lib/test_lib.ts'),
  nl('var IS_DARTIUM', 5, '/src/test_lib/test_lib.ts'),
  nl('class AsyncTestCompleter', 6, '/src/test_lib/test_lib.ts'),
  np('var jsmBeforeEach', [7, ct(1, '_global.beforeEach'), ct(16, 'jsmBeforeEach(() => { testBindings = []; });')], '/src/test_lib/test_lib.ts'),
  np('var jsmDescribe', [8, ct(1, '_global.describe')], '/src/test_lib/test_lib.ts'),
  np('var jsmDDescribe', [9, ct(1, '_global.fdescribe')], '/src/test_lib/test_lib.ts'),
  np('var jsmXDescribe', [10, ct(1, '_global.xdescribe')], '/src/test_lib/test_lib.ts'),
  np('var jsmIt', [11, ct(1, '_global.it')], '/src/test_lib/test_lib.ts'),
  np('var jsmIIt', [12, ct(1, '_global.fit')], '/src/test_lib/test_lib.ts'),
  np('var jsmXIt', [13, ct(1, '_global.xit')], '/src/test_lib/test_lib.ts'),
  np('var runnerStack', 14, '/src/test_lib/test_lib.ts'),
  np('var inIt', 15, '/src/test_lib/test_lib.ts'),
  np('var testBindings', 16, '/src/test_lib/test_lib.ts'),
  np('class BeforeEachRunner', [17, ctd(18, '_fns: List<FunctionWithParamTokens>'), ct(18, 'beforeEach()')], '/src/test_lib/test_lib.ts'),
  nl('class FunctionWithParamTokens', 18, '/src/test_lib/test_injector.ts'),
  np('function _describe', [19, ct(14, 'runnerStack.length, ...'), ct(17, 'new BeforeEachRunner')], '/src/test_lib/test_lib.ts'),
  nl('function describe', [20, ct(19, '_describe(jsmDescribe, ..'), ct(8, '_describe(jsmDescribe, ..')], '/src/test_lib/test_lib.ts'),
  nl('function ddescribe', [21, ct(19, '_describe(jsmDDescribe, ..'), ct(9, '_describe(jsmDDescribe, ..')], '/src/test_lib/test_lib.ts'),
  nl('function xdescribe', [22, ct(19, '_describe(jsmXDescribe, ..'), ct(10, '_describe(jsmXDescribe, ..')], '/src/test_lib/test_lib.ts'),
  nl('function beforeEach', [23, ct(14, 'runnerStack[runnerStack.length - 1], ...'), ct(18, 'FunctionWithParamTokens'), ct(7, 'jsmBeforeEach(fn)'), ct(35, 'fn = inject([], fn);')], '/src/test_lib/test_lib.ts'),
  nl('function beforeEachBindings', [24, ct(7, 'jsmBeforeEach(..'), ct(16, 'testBindings = ...')], '/src/test_lib/test_lib.ts'),
  np('function _it', [25, ct(14, ' = runnerStack[runnerStack.length - 1]'), ct(6, 'bind(AsyncTestCompleter).toFactory...'),
    ct(16, '*as argument'), ct(18, 'instanceof'), ct(15, 'inIt = ...'), ct(35, 'fn = inject([], fn);')
  ], '/src/test_lib/test_lib.ts'),
  nl('function it', [26, ct(25, '_it(jsmIt, ...'), ct(11, '_it(jsmIt, ...')], '/src/test_lib/test_lib.ts'),
  nl('function xit', [27, ct(25, '_it(jsmXIt, ...'), ct(13, '_it(jsmXIt, ...')], '/src/test_lib/test_lib.ts'),
  nl('function iit', [28, ct(25, '_it(jsmIIt, ...'), ct(12, '_it(jsmIIt, ...')], '/src/test_lib/test_lib.ts'),
  nl('interface GuinessCompatibleSpy extends jasmine.Spy', [29], '/src/test_lib/test_lib.ts'),
  nl('class SpyObject', [30, ct(29, '_createGuinnessCompatibleSpy')], '/src/test_lib/test_lib.ts'),
  np('function elementText', [31], '/src/test_lib/test_lib.ts'),
  nl('function isInInnerZone', [32, ct(34, '<NgZoneZone>global.zone...')], '/src/test_lib/test_lib.ts'),
  nl('function createTestInjector', [33], '/src/test_lib/test_injector.ts'),
  nl('class NgZoneZone', [34], '/src/core/zone/ng_zone.ts'),
  nl('function inject', [35], '/src/test_lib/test_injector.ts'),
]);
