var d = diagrams.box.generateDefinition,
    ds = function(lib) {
        return d(lib, s('libraries-' + lib));
    },
    c = diagrams.box.generateContainer,
    s = diagrams.shared.get;

diagrams.box({
    name: s('project') + ' used libraries',
    body: [
        c('npm', [
            c('dependencies', [
                d('es6-module-loader'),
                d('googleapis'),
                d('gulp-insert'),
                d('gulp-modify'),
                d('gulp-replace'),
                d('node-uuid'),
                d('reflect-metadata'),
                d('rx'),
                d('selenium-webdriver'),
                d('systemjs'),
                d('traceur'),
                d('which'),
                d('zone.js'),
            ]),
            c('devDependencies', [
                d('angular'),
                d('bower'),
                d('broccoli', "'Browser compilation library – an asset pipeline for applications that run in the browser'"),
                d('broccoli-filter'),
                d('broccoli-flatten'),
                d('broccoli-funnel'),
                d('broccoli-lodash'),
                d('broccoli-merge-trees'),
                d('broccoli-slow-trees'),
                d('broccoli-stew'),
                d('broccoli-writer'),
                d('canonical-path'),
                d('chokidar', "'A neat wrapper around node.js fs.watch / fs.watchFile / fsevents.'"),
                d('clang-format'),
                d('conventional-changelog'),
                d('css'),
                d('del'),
                d('dgeni'),
                d('dgeni-packages'),
                d('event-stream'),
                d('firefox-profile'),
                d('fs-extra'),
                d('glob'),
                d('gulp'),
                d('gulp-autoprefixer'),
                d('gulp-changed'),
                d('gulp-clang-format'),
                d('gulp-concat'),
                d('gulp-connect'),
                d('gulp-load-plugins'),
                d('gulp-rename'),
                d('gulp-sass'),
                d('gulp-shell'),
                d('gulp-sourcemaps'),
                d('gulp-template'),
                d('gulp-traceur'),
                d('gulp-typescript'),
                d('gulp-uglify'),
                d('gulp-webserver'),
                d('html2jade'),
                d('indent-string'),
                d('jasmine'),
                d('jasmine-core'),
                d('jpm'),
                d('js-beautify'),
                d('js-yaml'),
                d('karma'),
                d('karma-chrome-launcher'),
                d('karma-cli'),
                d('karma-dart'),
                d('karma-jasmine'),
                d('karma-sauce-launcher'),
                d('lodash'),
                d('madge', "'Create graphs from your CommonJS or AMD module dependencies'"),
                d('marked'),
                d('merge'),
                d('merge2'),
                d('minimatch'),
                d('minimist'),
                d('mock-fs'),
                d('node-html-encoder'),
                d('parse5'),
                d('protractor'),
                d('q'),
                d('react'),
                d('rewire'),
                d('run-sequence'),
                d('semver'),
                d('shelljs'),
                d('sorted-object'),
                d('source-map'),
                d('sprintf-js'),
                d('string'),
                d('strip-ansi'),
                d('symlink-or-copy'),
                d('systemjs-builder'),
                d('temp'),
                d('ternary-stream'),
                d('through2'),
                d('ts2dart'),
                d('tsd'),
                d('typescript'),
                d('vinyl', "'A virtual file format'"),
                d('walk-sync'),
                d('xtend'),
                d('yargs'),

            ])
        ]),
        c('bower', [
            d('polymer')
        ])
    ]
});
